### ISSUE TITLE
Question: Relaxation and Cost scaling are not supported?

### ISSUE THREAD

**Issue by m1093782566** [ICGog/Flowlessly#4]
Per the paper: `Firmament: Fast, Centralized Cluster Scheduling at Scale`, `Relaxation` and `Cost scaling` algorithms performs better than `Cycle canceling` and `Successive shortest path` algorithms. I just can't find `Relaxation` and `Cost scaling` in the solver. So, I am wondering why they are not supported in this project?

@ICGog @ms705

**Comment by ICGog** [comment]
Hi @m1093782566 ,

The algorithms are supported in Flowlessly, but they're not open source.

**Comment by m1093782566** [comment]
Thanks for your response @ICGog. So, how can I get the Flowlessly binary which supports `Relaxation` and `Cost Scaling` algorithms? I assume directly compiling from the source may does not work.
